rabbitCli dq TranslateArchiveVideoBulkQueue_TranslatorServiceBusClient
rabbitCli dq TranslateArchiveVideoQueue_TranslatorServiceBusClient
rabbitCli dq TranslateArchiveVideoRemovalQueue_TranslatorServiceBusClient
rabbitCli dq TranslateVpmsVideoBulkQueue_TranslatorServiceBusClient
rabbitCli dq TranslateVpmsVideoQueue_TranslatorServiceBusClient
rabbitCli dq TranslateVpmsVideoRemovalQueue_TranslatorServiceBusClient

rabbitCli dq EnricherCache-PartialV1-Queue
rabbitCli dq EnricherCache-RefreshV1-Queue
rabbitCli dq EnricherCache-RemoveV1-Queue

rabbitCli dq EnricherTextRazorTextQueue_EnricherServiceBusClient 
rabbitCli dq EnricherKitKeywordsVideoQueue_EnricherServiceBusClient
rabbitCli dq EnricherVideoPropertiesTextQueue_EnricherServiceBusClient

// rabbitCli dq EnricherAgencyPropertiesVideoQueue_EnricherServiceBusClient